disabled_rules:
  - vertical_whitespace
  - identifier_name
  - function_body_length
  - todo
  - cyclomatic_complexity
  - opening_brace
  - vertical_parameter_alignment

line_length: 120

included:
  - Contrast/Sources
  - ContrastHelper/Sources
