name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: macOS-12
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Build'
        run: NO_SIGNING=1 rake build | xcpretty
