name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: macOS-12
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: 'Select Xcode'
        run: sudo xcode-select -s /Applications/Xcode_13.4.1app
      - name: 'Build'
        run: NO_SIGNING=1 rake build
