name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: macOS-10.14
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: 'Select Xcode 10.3'
        run: sudo xcode-select -s /Applications/Xcode_10.3.app
      - name: 'Build'
        run: NO_SIGNING=1 rake build
