name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: macOS-10.14
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - name: 'Build'
        run: NO_SIGNING=1 rake build
